version: '3'
services:
  pyoff_main:
    build: .
    entrypoint: ["python", "./py-offline.py"]
    depends_on:
      - q
    restart: on-failure
    environment:
      PYOFF_URL: "https://google.com"
      PYOFF_DEPTH: 1
      PYOFF_DESTINATION: "site/"
      PYOFF_Q_HOST: "q"
      PYOFF_Q_FILES: "files"
  writer:
    build: .
    entrypoint: ["python", "./pyoffline_writer.py"]
    depends_on:
      - q
    restart: on-failure
    environment:
      PYOFF_DESTINATION: "site/"
      PYOFF_Q_HOST: "q"
      PYOFF_Q_FILES: "files"
  q:
    image: rabbitmq:3.8-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
