version: '3'
services:
  pyoff:
    build: .
    environment:
      PYOFF_URL: "https://amoustache.net"
      PYOFF_DEPTH: 1
      PYOFF_DESTINATION: "site/"
      LOGLEVEL: "INFO"
    volumes:
      - "./site:/usr/src/app/site"
